<?php
$companies = $this->companies;
$store = array();

foreach($companies as $companyOwner) {
    $companyColl = new HM_Model_Billing_Company_Collection();
    foreach($companyOwner->getOwnerAgreements() as $agreements) {
        $companyColl->load($agreements->getData('company_client'));
    }
    $store[] = array_merge($companyOwner->getData()->toArray(), array(
        'company_clients' => $companyColl->toArray()
    ));
}

$storeJson = Zend_Json::encode($store);
?>
<?php
$jScript = <<<JS
require([
    "dojo/dom",
    "dojo/html",
    "dojo/dom-class",
    "dojo/dom-construct",
    "dojo/dom-attr",
    "dojo/dom-form",
    "dojo/_base/array",
    "dojo/on",
    "dojo/_base/lang",
    "dojo/query",
    "dojo/router",
    "dojo/store/Memory",
    "dojo/aspect",
    "core/Layout",
    "core/helper/Validation",
    "core/helper/form",
    "core/helper/common",
    "dijit/Dialog",
    "core/Dispatcher",
    "dojo/Deferred",
    "core/widgets/SearchCompanyDialog"
], function(dom, domHtml, domClass, domConstruct, domAttr, domForm, array, on, lang, query, router, storeMemory, aspect, coreLayout,
coreValidation, coreHelperForm, coreHelperCommon, dijitDialog, coreDispatcher, Deferred, coreSearchCompanyDialog){
    dojo.ready(function(){

        var Layout = new coreLayout({
            messenger: {
                node: dom.byId('messenger')
            },
            processing: {
                node: dom.byId('loader')
            }
        });

        (function(){
            var storeTest = new storeMemory({
                data: [
                    {id: 1, name: "one", prime: false},
                    {id: 2, name: "two", even: true, prime: true},
                    {id: 3, name: "three", prime: true},
                    {id: 4, name: "four", even: true, prime: false},
                    {id: 5, name: "five", prime: true}
                ]
            });


        })(

        );

        dojo.subscribe('getCompaniesClients', function(deferred){
            deferred.then(function(response){
                query('.toggle').forEach(function(item){
                    var handle = on(item, 'click', function(event){
                        handle.remove();
                        // Построить вторичное дерево Компаний-Контрагентов
                        var html = '';
                        array.forEach(response.companiesClientsStore.data, function(item){
                            html += Handlebars.compile(dojo.byId("company-client-item").innerHTML)(item);
                        });
                        var tbody = query('tbody', dom.byId("#company-owner-" + response.owner)).pop();
                        domConstruct.place(html, tbody);

                        query('span [class^="toggle-"', item).forEach(function(spanItem){
                            domClass.toggle(spanItem, "hidden");
                        });

/*                        on(item, 'click', function(){
                            if(domClass.contains(tbody, "hidden")){
                                domClass.remove(tbody, "hidden");
                                query(tbody)
                            } else {
                                domClass.add(tbody, "hidden");

                            }


                        });*/
                    });
                });
            });

        });

        coreDispatcher.register('getCompaniesClients', function(routeEvent){
            Layout.load({
                url:    Layout.baseUrl('manager/billing/get-companies-clients'),
                format: 'json'
            }).then(function(response){
                var deferred = new Deferred();
                dojo.publish('getCompaniesClients', deferred);
                deferred.resolve({
                    companyOwner: 16,
                    companiesClientsStore: new storeMemory({
                        idProperty: 'id',
                        data: response.data['companies']
                    })
                });

                // Построить список Компаний Владельцев


 /*                // Построить список Контрагентов
                array.forEach(companyOwnerClientBundleStore.data, function(item){
                    var table = query('#company-owner-' + item['owner'])[0];
                    console.log(item);
                    var handler = on(query('.toggle', table)[0], 'click', function(){
                        var html = '';
                        array.forEach(item['clients'], function(item2){
                            html += Handlebars.compile(dojo.byId("new-company-client-item2").innerHTML)(companiesStore.get(item2));
                        });
                        domConstruct.place(html, query('tbody', table)[0]);
                        handler.remove();
                    });
                   query('#company-owner-' + item.owner + ' > tbody .toggle').on.once('click', function(event){
                        var html = '';
                        array.forEach(companyOwnerClientBundleStore.data['clients'], function(item){
                            html += Handlebars.compile(dojo.byId("new-company-client-item2").innerHTML)(companiesStore.get(item));
                        });
                        domHtml.place(query('#company-owner-' + item.id + ' > tbody')[0], html);
                        on(event.target, 'click', function(){
                            domClass.toggle(query('#company-owner-' + item.id + ' > tbody')[0], "hidden");
                        });
                    });
                });
*/
                // Получить список контрагенов и обработать их


            });
        }, true);

        coreDispatcher.startup();
        router.go('getCompaniesClients');

    });
});

JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript')
?>
<div id="contentCompanies">
    <table class="table table-bordered" id="company-owner-16">
        <colgroup>
            <col width="50"/>
            <col width="650"/>
            <col/>
        </colgroup>
        <thead>
            <tr>
                <td colspan="3">
                    {{data.name}} ({{data.inn}} / {{data.kpp}})
                </td>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3"><a class="toggle"><span class="toggle-show">развернуть</span><span class="hidden toggle-hide">свернуть</span></a><span> | </span><a>+ новый конрагент</a></td>
            </tr>
        </tfoot>
        <tbody class="hidden">
            <tr>
                <th>#ID</th>
                <th>Контрагент</th>
                <th>Опции</th>
            </tr>
        </tbody>
    </table>
</div>

<script id="company-client-item" type="text/x-handlebars-template">
    <tr>
        <td>{{id}}</td>
        <td>
            {{data.name}} ({{data.inn}} / {{data.kpp}})
        </td>
        <td>
            <a>+ новый договор</a> <a>договора</a>
        </td>
    </tr>
</script>