<?php
$agreement = $this->agreement;
?>
<form id="edit-agreement-subscribers">
    <table class="table table-bordered">
        <colgroup>
            <col width="50"/>
            <col width="50"/>
            <col width="200"/>
            <col width="200"/>
            <col/>
        </colgroup>
        <thead>
            <tr>
                <th colspan="5">Активные подписчики</th>
            </tr>
            <tr>
                <th>#ID</th>
                <th>#</th>
                <th>Логин</th>
                <th>Email</th>
                <th>Ф.И.О</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="5">
                    <input type="hidden" name="agreement" value="<?=$agreement->getData('id')?>">
                    <button type="button" name="add" data-action="addSubscriber/<?=$agreement->getData('id')?>">Добавить</button>
                    <button type="button" name="remove">Удалить</button>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach($agreement->getSubscription()->getUsers() as $user): ?>
            <tr>
                <td><?=$user->getData('id')?></td>
                <td>
                    <input type="checkbox" name="users[]" value="<?=$user->getData('id')?>"/>
                </td>
                <td><?=$user->getData('login')?></td>
                <td><?=$user->getData('email')?></td>
                <td><?=$user->getData('last_name')?> <?=$user->getData('first_name')?> <?=$user->getData('middle_name')?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</form>

<form id="edit-agreement-invited-subscribers">
    <table class="table table-bordered">
        <colgroup>
            <col width="50"/>
            <col width="50"/>
            <col width="300"/>
            <col/>
        </colgroup>
        <thead>
        <tr>
            <th colspan="4">Приглашенные подписчики</th>
        </tr>
        <tr>
            <th>#ID</th>
            <th>#</th>
            <th>Email</th>
            <th>Ф.И.О</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="5">
                <input type="hidden" name="agreement" value="<?=$agreement->getData('id')?>">
                <button type="button" name="add">Добавить</button>
                <button type="button" name="remove">Удалить приглашения</button>
                <button type="button" name="remove">Отправить приглашения повторно</button>
            </td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach($agreement->getSubscription()->getGuests() as $guest): ?>
            <tr>
                <td><?=$guest->getData('id')?></td>
                <td>
                    <input type="checkbox" name="users[]" value="<?=$user->getData('id')?>"/>
                </td>
                <td><?=$guest->getData('email')?></td>
                <td><?=$guest->getData('last_name')?> <?=$guest->getData('first_name')?> <?=$guest->getData('middle_name')?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</form>
