<?php
$agreements = $this->agreements;
$lineColl = new HM_Model_Counseling_Structure_Line_Collection();
?>
<table class="table table-bordered">
    <colgroup>
        <col width="50"/>
        <col width="350"/>
        <col width="350"/>
        <col width="100"/>
        <col width="100">
        <col/>
        <col/>
    </colgroup>
    <thead>
        <tr>
            <th>#ID</th>
            <th>ЛК</th>
            <th>Тариф</th>
            <th>Начало</th>
            <th>Окончание</th>
            <th>Истекает (дн.)</th>
            <th>Опции</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="7">
                <button type="button" data-action="addAgreement/12/26">Новый договор</button>
            </td>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach($agreements as $agreement): ?>
        <tr>
            <td><?=$agreement->getData('id')?></td>
            <td><?=$agreement->getTariff()->getLine()->getData('name')?></td>
            <td><?=$agreement->getTariff()->getData('name')?></td>
            <td><?=date("d.m.Y", $agreement->getData('date_begin'))?></td>
            <td><?=date("d.m.Y", $agreement->getData('date_end'))?></td>
            <td>
                <?php
                    $days = ceil(($agreement->getData('date_end') - date('U')) / 86400);
                ?>
                <?php if($days > 0): ?>
                    <?=$days?>
                <?php else: ?>
                    <span style="color: #cc0000"><?=abs($days)?> (просрочен)</span>
                <?php endif; ?>
            </td>
            <td><a data-action="getAgreementBoard/<?=$agreement->getData('id')?>">просмотр</td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>