<p><strong>Oops! 403: <?php echo $this->message ?></strong></p>
<p>
    У вашего аккаунта отсутствуют права на просмотр или редактирование запрошенного ресурса.
</p>
<p>
    За соответствующими правами обратитесь к администраторам системы или компании-партнера<br/>
</p>
<?php if(!HM_Model_Account_Auth::getInstance()->isAuth()): ?>
<a href="<?=$this->baseUrl('account/access/login');?>">Авторизоваться</a>
<span> / </span>
<?php endif; ?>
<a href="<?=$this->baseUrl();?>">Вернуться на главную</a>