<form id="add-manager">
<table class="table table-bordered">
    <colgroup></colgroup>
    <thead></thead>
    <tfoot>
        <tr>
            <td>
                <button type="button" name="send">Сохранить</button>
            </td>
        </tr>
    </tfoot>
    <tbody>
        <tr>
            <td>
                <input type="checkbox" value="fff" name="check">
                <label for="add-manager-account">Логин или email</label>
                <input type="text" id="add-manager-account" name="account" isRequired="true">
            </td>
        </tr>
        <tr>
            <td>
                <em>Пользователь не выбран</em>
            </td>
        </tr>
        <tr>
            <td>
                <label for="add-manager-company">Компания</label>
                <select name="company" id="add-manager-company"><option value=1>Test</option></select>
            </td>
        </tr>
    </tbody>
</table>
</form>