<?php
$companies = $this->companies;
$companyColl = new HM_Model_Billing_Company_Collection();
?>
<form id="add-manager">
<table class="table table-bordered">
    <colgroup></colgroup>
    <thead></thead>
    <tfoot>
        <tr>
            <td>
                <button type="button" name="send">Сохранить</button>
            </td>
        </tr>
    </tfoot>
    <tbody>
        <tr>
            <td>
                <label for="add-manager-account">Логин или email:</label>
                <input type="text" id="add-manager-account" name="account" required="true">
            </td>
        </tr>
        <tr>
            <td>
                <label for="add-manager-company">Компания:</label>
                <select name="company" id="add-manager-company">
                    <?php foreach($companies as $id): ?>
                        <?php
                            $company = $companyColl->load($id);
                        ?>
                        <option value="<?=$company->getData('id');?>"><?=$company->getData('name')?></option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
    </tbody>
</table>
</form>