<?php
// Сгруппировать возможности
$possibilityGroupByRole = array();
foreach($this->possibilities as $possibility) {
    $possibilityGroupByRole[$possibility->getData('role')->get('code')][] = $possibility;
}
$companyColl = new HM_Model_Billing_Company_Collection();
$access = HM_Model_Account_Access::getInstance();
$manager = $this->manager;
?>
<form id="edit-manager-possibility">
<table class="table table-bordered">
    <colgroup>
        <col width="300"/>
        <col/>
    </colgroup>
    <thead>
    <tr>
        <th colspan="3">
            <?=$manager->getData('email');?> (<?=$manager->getData('last_name');?> <?=$manager->getData('first_name');?> <?=$manager->getData('middle_name');?>)
        </th>
    </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="3">
                <button type="button" data-action="addPossibility/<?=$manager->getData('id')?>">Добавить</button>
            </td>
        </tr>
    </tfoot>
    <tbody>
    <?php foreach($possibilityGroupByRole as $roleIdentifier => $possibilities): ?>
    <?php if(count($possibilities) > 0): ?>
    <tr>
        <td rowspan="<?=count($possibilities) + 1 ?>"><?=$access->getRole($roleIdentifier)->get('name')?></td>
        <th>Компании</th>
        <th>Опции</th>
    </tr>
    <?php foreach($possibilities as $possibility): ?>
    <tr>
        <td>
            <?=$companyColl->load($possibility->getData('company'))->getData('name')?>
        </td>
        <td>
        <?php if($roleIdentifier != 'ADM_COMPANY'): ?>
            <a data-action="editPossibilityObjects/<?=$possibility->getData('id')?>">ресурсы</a> |
        <?php endif; ?>
            <a data-action="removePossibility/<?=$possibility->getData('id')?>">удалить</a>
        </td>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>
</form>