<?php
$data = $this->data;
$manager = HM_Model_Account_User::load($data['manager']);



$roles = array();
$account = HM_Model_Account_Auth::getInstance()->getAccount();
$access = HM_Model_Account_Access::getInstance();

$user = HM_Model_Account_User::load($account['user']);
foreach(array_keys($user->getRoles()) as $roleIdentifier) {
    $roles = array_merge(
        $roles,
        $access->getInheritsRoles($access->getRole($roleIdentifier), true),
        array($access->getRole($roleIdentifier))
    );
}
// Исключить повторяющиеся роли.
$index = array();
$_roles = $roles;
foreach($_roles as $key => $role) {
    if(in_array($role->get('id'), $index)) {
        unset($roles[$key]);
        continue;
    }
    $index[] = $role->get('id');
}
Zend_Debug::dump($roles);
?>
<form id="edit-manager-possibility">
<table class="table table-bordered">
    <colgroup>
        <col width="300"/>
        <col/>
    </colgroup>
    <thead>
    <tr>
        <th colspan="2"><?=$manager->getData('email');?> (<?=$manager->getData('last_name');?> <?=$manager->getData('first_name');?> <?=$manager->getData('middle_name');?>) </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($data['roles'] as $roleIdentifier => $companies): ?>
    <tr>
        <td rowspan="<?=count($companies) + 1 ?>"><?=$access->getRole($roleIdentifier)->get('name')?></td>
        <th>Компании</th>
    </tr>
    <?php foreach($companies as $company): ?>
    <tr>
        <td>
            <a data-action="editPossibilityObjects/"><?=HM_Model_Billing_Company::load($company)->getData('name')?></a>
        </td>
    </tr>
    <?php endforeach; ?>
    <tr>
        <td colspan="2"><button type="button">Добавить компанию</button></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</form>