<?php
$jScript = <<<JS
require(["dojo/behavior", "core/Sandbox", "core/sandbox/layout/Dialog"]);
dojo.ready(function(){

});

JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript')
?>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Пользователь</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="2">
                <button type="button" name="add">Добавить</button>
                <button type="button" name="remove">Удалить</button>
            </td>
        </tr>
    </tfoot>
    <tbody>
        <tr></tr>
    </tbody>
</table>