<?php
$data = $this->data;
?>
<?php
$jScript = <<<JS
require([
    "dojo/dom",
    "dojo/dom-form",
    "dojo/on",
    "dojo/_base/lang",
    "dojo/query",
    "dojo/router",
    "core/Layout",
    "core/helper/Validation",
    "dijit/Dialog"
], function(dom, domForm, on, lang, query, router, coreLayout, coreValidation, dijitDialog){
    dojo.ready(function(){

        var Layout = new coreLayout({
            timeout: 3000,
            messenger: {
                node: dom.byId('messenger')
                },
            processing: {
                node: dom.byId('loader')
                }
        });

        var DialogBox = new dijitDialog();

        // #main
        router.register('main', function(){
            query('[data-action^="getManager/"]').on('click', function(event){
                event.preventDefault();
                router.go(event.target.getAttribute("data-action"));
            });

            query('[data-action^="addManager"]').on('click', function(event){
                event.preventDefault();
                Layout.load({
                    url:    appConfig.baseUrl + '/manager/possibility/add-manager',
                    format: 'html'
                }).then(function(response){
                    DialogBox.set('content', response);
                    DialogBox.set('title', "Добавление менеджера");
                    DialogBox.show();
                }).then(function(){
                    on(dom.byId("add-manager")['send'], 'click', function(event){
                        event.preventDefault();
                        //var formObject = domForm.toObject(event.target.form);
                        console.log(domForm.toObject(event.target.form));
                        //if(formObject['account'].length && formObject['company'])
/*                        Layout.send({
                            url:    appConfig.baseUrl + '/manager/possibility/add-manager',
                            args:   formObject
                        });*/
                      });
                })
            });

        });

        router.register('getManager/:manager', function(event){
            Layout.load({
                url:    '../../../manager/possibility/get-manager',
                format: 'html',
                args:   event.params
            }).then(function(response){
                Layout.place(dom.byId('contentManagers'), response);
            }).then(function(){
                // Навешиваем события
                query('[data-action^="edit-possibility-objects"]').on('click', function(event){
                    event.preventDefault();
                });
            })
        });

        // Startup must be called in order to "activate" the router
        router.startup();
        router.go('main');

    });
});

JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript')
?>
<div id="contentManagers">
    <table class="table table-bordered">
        <colgroup>
            <col width="50">
            <col>
        </colgroup>
        <thead>
            <tr>
                <th>#</th>
                <th>Пользователь</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="2">
                    <button type="button" data-action="addManager" name="add">Добавить</button>
                    <button type="button" data-action="removeManager" name="remove" id="testme">Удалить</button>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach($data['managers'] as $manager): ?>
            <tr>
                <td><input type="checkbox"/></td>
                <td><a data-action="getManager/<?=$manager->get('id')?>"><?=$manager->get('email')?></a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>