<?php
$rolesArray = array();
$userColl = new HM_Model_Account_User_Collection();
$companyColl = new HM_Model_Billing_Company_Collection();
$possibilities = $this->possibilities;

// Справочник ролей
foreach(HM_Model_Account_Access::getInstance()->getRoles() as $role) {
    $rolesArray[] = $role->toArray();
}


// Список менеджеров
foreach($possibilities as $possibility) {
    $userColl->load($possibility['user']);
}

$rolesJson = Zend_Json::encode($rolesArray);

$referenceRC = Zend_Json::encode($this->referenceRC);


$hierarchyRoleAndCompanies = array();
foreach($this->hierarchyRoleAndCompanies as $roleIdentifier => $companies) {
    $hierarchyRoleAndCompanies[] = array(
        'code'      => $roleIdentifier,
        'companies' => $companies
    );
    foreach($companies as $company) {
        $companyColl->load($company);
    }
}
$companiesJson = Zend_Json::encode($companyColl->toArray());
$hierarchyRoleAndCompaniesJson = Zend_Json::encode($hierarchyRoleAndCompanies);

?>
<?php
$jScript = <<<JS
require([
    "dojo/dom",
    "dojo/dom-attr",
    "dojo/dom-form",
    "dojo/on",
    "dojo/_base/lang",
    "dojo/query",
    "dojo/router",
    "dojo/store/Memory",
    "core/Layout",
    "core/helper/Validation",
    "dijit/Dialog"
], function(dom, domAttr, domForm, on, lang, query, router, storeMemory, coreLayout, coreValidation, dijitDialog){
    dojo.ready(function(){

        var Layout = new coreLayout({
            messenger: {
                node: dom.byId('messenger')
                },
            processing: {
                node: dom.byId('loader')
                }
        });

        // Хранилище системных ролей
        var storeRoles = new storeMemory({data: $rolesJson});

        // Хранилище информации о компаниях доступных текущему администратору
        var storeCompanies = new storeMemory({data: $companiesJson});

        // Связка связи Роль-Компания
        var storeHierarchyRoleAndCompanies = new storeMemory({data: $hierarchyRoleAndCompaniesJson});

        var DialogBox = new dijitDialog();

        // #Страница с менеджерами
        router.register('main', function(){
            // Получение менеджера
            query('[data-action^="getManagerBoard/"]').on('click', function(event){
                event.preventDefault();
                router.go(event.target.getAttribute("data-action"));
            });

            query('[data-action^="addPossibility"]').on('click', function(event){
                event.preventDefault();
                dojo.publish('addPossibility');
            });
        });

        // #Страница с настройками одного менеджера
        router.register('getManagerBoard/:manager', function(event){
            dojo.publish('getManagerBoard', event.params);
        });

        // Startup must be called in order to "activate" the router
        router.startup();
        router.go('main');

        dojo.subscribe('getManagers', function(){

        });

        dojo.subscribe('getManagerBoard', function(args){
            Layout.load({
                url:    '../../../manager/possibility/get-manager-board',
                format: 'html',
                args:   args
            }).then(function(response){
                Layout.place(dom.byId('contentManagers'), response);
            }).then(function(){
                // Навешиваем события
                query('[data-action^="editPossibilityObjects"]').on('click', function(event){
                    event.preventDefault();
                    dojo.publish('editPossibilityObjects', {possibility: domAttr.get(event.target, "data-action").split('/')[1]});
                });
            }).then(function(){
                query('[data-action^="addPossibility"]').on('click', function(event){
                    event.preventDefault();
                    dojo.publish('addPossibility', {manager: domAttr.get(event.target, "data-action").split('/')[1]});
                });
            }).then(function(){
                query('[data-action^="removePossibility"]').on('click', function(event){
                    event.preventDefault();
                    dojo.publish('removePossibility', {
                            possibility: domAttr.get(event.target, "data-action").split('/')[1],
                            manager: args['manager']
                        }
                    );
                });
            })
        });

        // Действие на редактирование объектов
        dojo.subscribe('editPossibilityObjects', function(args){
            Layout.load({
                url:    appConfig.baseUrl + '/manager/possibility/edit-possibility-objects',
                format: 'html',
                args:   args
            }).then(function(response){
                DialogBox.set('content', response);
                DialogBox.set('title', "Редактирование ресурсов");
                DialogBox.show();
            }).then(function(){
                on(dom.byId('_d_'), 'click', function(event){
                    Layout.send({
                        url:    appConfig.baseUrl + '/manager/possibility/edit-possibility-objects',
                        args:   domForm.toObject(event.target.form)
                    }).then(function(response){
                        if(response.result && response.result != -1) {
                            DialogBox.hide();
                        }
                    });
                })
            })
        });

        dojo.subscribe('removePossibility', function(args){
            Layout.send({
                url:    appConfig.baseUrl + '/manager/possibility/remove-possibility',
                args:   args
            }).then(function(response){
                if(response.result && response.result != -1) {
                    dojo.publish('getManagerBoard', args);
                }
            })
        });

        // Действие на добавление нового Possibility
        dojo.subscribe('addPossibility', function(args){
            Layout.load({
                url:    appConfig.baseUrl + '/manager/possibility/add-possibility',
                format: 'html',
                args:   args
            }).then(function(response){
                DialogBox.set('content', response);
                DialogBox.set('title', "Редактирование ресурсов");

                var form = dom.byId('add-possibility');
                var Validation = new coreValidation(form);
                var formEvents = {
                    changeRole: function(){
                        storeHierarchyRoleAndCompanies.query({'code': storeRoles.get(domForm.fieldToObject(form['possibility[role]']))['data']['code']}).forEach(function(items){
                            var html = '';
                            dojo.forEach(items['companies'], function(company){
                                html += '<option value="' + company + '" >' + storeCompanies.get(company)['data']['name'] + '</option>';
                            });
                            form['possibility[company]'].length = 0;
                            form['possibility[company]'].innerHTML = html;
                        });
                    },
                    onSend: function(){
                        if(Validation.isValid()) {
                            Layout.send({
                                url:    appConfig.baseUrl + '/manager/possibility/add-possibility',
                                args:   domForm.toObject(form)
                            }).then(function(response){
                                 if(response.result && response.result != -1) {
                                    DialogBox.hide();
                                    setTimeout(function(){
                                        dojo.publish('getManagerBoard', {manager: domForm.fieldToObject(form['possibility[user]'])});
                                    }, Layout._delay);
                                } else {
                                    Validation.clear();
                                    Validation.setMessages(response.error);
                                }
                            });
                        }
                    }
                };

                on(form['possibility[role]'], 'change', formEvents.changeRole);
                on(form['send'], 'click', formEvents.onSend);

                (function(){
                    formEvents.changeRole();
                    DialogBox.show();
                })();
            });
        });

    });
});

JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript')
?>
<div id="contentManagers">
    <table class="table table-bordered">
        <colgroup>
            <col width="50">
            <col>
        </colgroup>
        <thead>
            <tr>
                <th>#</th>
                <th>Пользователь</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="2">
                    <button type="button" data-action="addPossibility" name="add">Добавить</button>
                    <button type="button" data-action="removeManager" name="remove" id="testme">Удалить</button>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach($userColl->getDataIterator() as $manager): ?>
            <tr>
                <td><input type="checkbox"/></td>
                <td><a data-action="getManagerBoard/<?=$manager->get('id')?>"><?=$manager->get('email')?></a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>