<p style="text-transform: uppercase; font-weight: bold">Авторизация</p>
<p><em>Для продолжения работы в системе HelpMe, пожалуйста, авторизуйтесь</em></p>
<div style="margin-top: 20px">
    <form method="post" action="<?=$this->url()?>">
        <p>
            <label class="required" for="account-login"><strong>Логин:</strong></label>
            <input type="text" value="" id="account-login" name="account[login]" style="width: 90%" >
        </p>
        <p>
            <label class="required" for="account-password"><strong>Пароль:</strong></label>
            <input type="password" value="" id="account-password" name="account[password]" style="width: 90%">
        </p>
        <p>
            <button type="submit" id="send" name="send">Войти в систему</button>
        </p>
    </form>
</div>
