<?php
$tariff = $this->data;
Zend_Debug::dump($tariff);

?>
<?php if($tariff instanceof HM_Model_Billing_Tariff): ?>
<form id="edit-tariff-info">
    <input type="hidden" class="hidden" name="tariff[id]" value="<?=$tariff->getData('id')?>">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th colspan="4"><h3>Редактирование тарифа «<?=$tariff->getData('name')?>»</h3></th>
            </tr>
                <?php if($tariff->getData('used')): ?>
            <tr>
                <td colspan="3">
                    <div class="alert alert-info" style="margin: 0">
                        <strong>Внимание!</strong> Вы работаете в ограниченном режиме редактирования тарифа.<br/>
                        Это означает, что данный тариф уже используется в одном из договоров.
                    </div>
                </td>
            </tr>
                <?php endif; ?>
        </thead>
        <tbody>
        <tr>
            <td>
                <strong>Название тарифа: </strong>«<?=$tariff->getData('name')?>»
            </td>
        </tr>
        <tr>
            <td>
                <label for="edit-tariff-description"><strong>Описание:</strong></label>
                <textarea name="tariff[description]" id="edit-tariff-description" cols="1" rows="4" style="width: 700px; max-width: 700px; min-width: 700px"><?=$tariff->getData('description')?></textarea>
            </td>
        </tr>
        </tbody>
    </table>
    <strong>Общие настройки</strong>
    <table class="table table-bordered">
        <colgroup>
            <col width="25%">
            <col width="25%">
            <col width="25%">
            <col>
        </colgroup>
        <tbody>
            <tr>
                <td>
                    <input type="hidden" name="tariff[active]" value="0"/>
                    <input type="checkbox" name="tariff[active]" id="edit-tariff-active"
                        <?=$tariff->getData('active') ? "checked=\"true\"" : ""; ?> value="1" />
                    <label for="edit-tariff-active" class="inline">Активен</label>
                </td>
                <td>
                    <input type="hidden" name="tariff[not_available]" value="0"/>
                    <input type="checkbox" name="tariff[not_available]" id="edit-tariff-not-available"
                        <?=$tariff->getData('not_available') ? "checked=\"true\"" : ""; ?> value="1" />
                    <label for="edit-tariff-not-available" class="inline">Доступен клиенту</label>
                </td>
                <td>
                    <input type="hidden" name="tariff[need_committer]" value="0"/>
                    <input type="checkbox" name="tariff[need_committer]" id="edit-tariff-need-committer"
                        <?=$tariff->getData('need_committer') ? "checked=\"true\"" : ""; ?> value="1" />
                    <label for="edit-tariff-need-committer" class="inline">Требует подтверждения админ. ЛК</label>
                </td>
                <td>
                    <input type="hidden" name="tariff[specchoice]" value="0"/>
                    <input type="checkbox" name="tariff[specchoice]" id="edit-tariff-specchoice"
                        <?=$tariff->getData('specchoice') ? "checked=\"true\"" : ""; ?> value="1" />
                    <label for="edit-tariff-specchoice" class="inline">Доступен выбор специалиста</label>
                </td>
            </tr>
        </tbody>
    </table>
    <table class="table table-bordered">
        <colgroup>
            <col width="25%">
            <col width="25%">
            <col width="25%">
            <col>
        </colgroup>
        <tbody>
            <tr>
                <td>Стоимость тарифа (руб.):</td>
                <td>
                    <?php if($tariff->getData('used')): ?>
                        <?=$tariff->getData('price')?>
                    <?php else: ?>
                        <label for="edit-tariff-price" class="field-editable"><span style="width: 60px;">[ <?=$tariff->getData('price')?> ] </span></label>
                        <input type="text" name="price" class="hidden" id="edit-tariff-price" value="<?=$tariff->getData('price')?>"/>
                    <?php endif; ?>
                </td>
                <td>Приоритет в очереди (0-127)</td>
                <td>
                    <label for="edit-tariff-queue-priority" class="field-editable"><?=$tariff->getData('queue_priority')?></label>
                    <input type="text" name="tariff[queue_priority]" class="hidden" id="edit-tariff-queue-priority" value="<?=$tariff->getData('queue_priority')?>" maxlength="3"/>
                </td>
            </tr>
            <tr>
                <td>Количество минут:</td>
                <td>
                    <?php if($tariff->getData('used')): ?>
                        <?=$tariff->getData('minute_count')?>
                    <?php else: ?>
                        <label for="edit-tariff-minute-count" class="field-editable"><?=$tariff->getData('minute_count')?></label>
                        <input type="text" name="tariff[minute_count]" class="hidden" id="edit-tariff-minute-count" value="<?=$tariff->getData('minute_count')?>" />
                    <?php endif; ?>
                </td>
                <td>Количество писем:</td>
                <td>
                    <?php if($tariff->getData('used')): ?>
                        <?=$tariff->getData('message_count')?>
                    <?php else: ?>
                        <label for="edit-tariff-message-count" class="field-editable"><?=$tariff->getData('message_count')?></label>
                        <input type="text" name="tariff[message_count]" class="hidden" id="edit-tariff-message-count" value="<?=$tariff->getData('message_count')?>"/>
                    <?php endif; ?>
                </td>
            </tr>
        </tbody>
    </table>
    <table class="table table-bordered">
        <colgroup>
            <col style="width: 33%">
        </colgroup>
        <thead>
        <tr>
            <th colspan="3">Настройка консультаций</th>
        </tr>
        <tr>
            <td>
                <input type="hidden" name="tariff[consultation_enabled]" value="0"/>
                <input type="checkbox" name="tariff[consultation_enabled]" id="edit-tariff-consultation-enabled"
                    <?=$tariff->getData('consultation_enabled') ? "checked=\"true\"" : ""; ?> value="1"
                    <?=$tariff->getData('used') ? "disabled=\"true\"" : "" ?> />
                <label for="edit-tariff-consultation-enabled" class="inline">Консультации разрешены</label>
            </td>
            <td>
                <input type="hidden" name="tariff[consultation_unlimited]" value="0"/>
                <input type="checkbox" name="tariff[consultation_unlimited]" id="edit-tariff-consultation-unlimited"
                    <?=$tariff->getData('consultation_unlimited') ? "checked=\"true\"" : ""; ?> value="1"
                    <?=$tariff->getData('used') ? "disabled=\"true\"" : "" ?> />
                <label for="edit-tariff-consultation-unlimited" class="inline">Консультации без ограничений</label>
            </td>
            <td>
                <input type="hidden" name="tariff[auto_prolongate]" value="0"/>
                <input type="checkbox" name="tariff[auto_prolongate]" id="edit-tariff-auto-prolongate"
                    <?=$tariff->getData('auto_prolongate') ? "checked=\"true\"" : ""; ?> value="1"
                    <?=$tariff->getData('used') ? "disabled=\"true\"" : "" ?> />
                <label for="edit-tariff-auto-prolongate" class="inline">Автопродление</label>
            </td>
        </tr>
        </thead>
    </table>
    <table class="table table-bordered">
        <colgroup>
            <col width="25%">
            <col width="25%">
            <col width="25%">
            <col>
        </colgroup>
        <tbody>
            <tr>
                <td>Мин. продолжительность (сек):</td>
                <td>
                    <?php if($tariff->getData('used')): ?>
                        <?=$tariff->getData('tmin')?>
                    <?php else: ?>
                        <label for="edit-tariff-tmin" class="field-editable"><?=$tariff->getData('tmin')?></label>
                        <input type="text" class="hidden" name="tariff[tmin]" id="edit-tariff-tmin" value="<?=$tariff->getData('tmin')?>"/>
                    <?php endif; ?>
                </td>
                <td>Мин. тарифицируемое время (сек.):</td>
                <td>
                    <?php if($tariff->getData('used')): ?>
                        <?=$tariff->getData('tqmin')?>
                    <?php else: ?>
                        <label for="edit-tariff-tqmin" class="field-editable"><?=$tariff->getData('tqmin')?></label>
                        <input type="text" class="hidden" name="tariff[tqmin]" id="edit-tariff-tqmin" value="<?=$tariff->getData('tqmin')?>"/>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td>Кратность отсчета времени (сек.):</td>
                <td>
                    <?php if($tariff->getData('used')): ?>
                        <?=$tariff->getData('tquant')?>
                    <?php else: ?>
                        <label for="edit-tariff-tquant" class="field-editable"><?=$tariff->getData('tquant')?></label>
                        <input type="text" name="tariff[tquant]" class="hidden" id="edit-tariff-tquant" value="<?=$tariff->getData('tquant')?>"/>
                    <?php endif; ?>
                </td>
                <td>Стоимость минуты (руб.):</td>
                <td>
                    <?php if($tariff->getData('used')): ?>
                        <?=$tariff->getData('minute_price')?>
                    <?php else: ?>
                        <label for="edit-tariff-minute-price" class="field-editable"><?=$tariff->getData('minute_price')?></label>
                        <input type="text" name="tariff[minute_price]" class="hidden" id="edit-tariff-minute-price" value="<?=$tariff->getData('minute_price')?>"/>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td>Срок реакции на консультации (сек.):</td>
                <td>
                    <label for="edit-tariff-consultation-response" class="field-editable"><?=$tariff->getData('consultation_response')?></label>
                    <input type="text" name="tariff[consultation_response]" class="hidden" id="edit-tariff-consultation-response" value="<?=$tariff->getData('consultation_response')?>" maxlength="8" onclick="formatTime(this);"/>
                </td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
    <table class="table table-bordered">
        <colgroup>
            <col width="25%">
            <col width="25%">
            <col width="25%">
            <col>
        </colgroup>
        <thead>
            <tr>
                <th colspan="4">Настройка сообщений</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Сообщения разрешены:</td>
                <td>
                    <input type="radio" name="tariff[message_enabled]" id="edit-tariff-message-enabled-yes"
                        <?=$tariff->getData('message_enabled') ? "checked=\"true\"" : ""; ?> value="true"
                        <?=$tariff->getData('used') ? "disabled=\"true\"" : "" ?>/> Да
                    <input type="radio" name="tariff[message_enabled]" id="edit-tariff-message-enabled-no"
                        <?=!$tariff->getData('message_enabled') ? "checked=\"true\"" : ""; ?> value="false"
                        <?=$tariff->getData('used') ? "disabled=\"true\"" : "" ?>/> Нет
                </td>
                <td>Сообщения без ограничений</td>
                <td>
                    <input type="radio" name="tariff[message_unlimited]" id="edit-tariff-message-unlimited-yes"
                        <?=$tariff->getData('message_unlimited') ? "checked=\"true\"" : ""; ?> value="true"
                        <?=$tariff->getData('used') ? "disabled=\"true\"" : "" ?>/> Да
                    <input type="radio" name="tariff[message_unlimited]" id="edit-tariff-message-unlimited-no"
                        <?=!$tariff->getData('message_unlimited') ? "checked=\"true\"" : ""; ?> value="true"
                        <?=$tariff->getData('used') ? "disabled=\"true\"" : "" ?>/> Нет
                </td>
            </tr>
            <tr>
                <td>Стоимость сообщения (руб.):</td>
                <td>
                    <?php if($tariff->getData('used')): ?>
                    <?=$tariff->getData('message_price')?>
                    <?php else: ?>
                    <label for="edit-tariff-message-price" class="field-editable"><?=$tariff->getData('message_price')?></label>
                    <input type="text" name="tariff[message_price]" class="hidden" id="edit-tariff-message-price" value="<?=$tariff->getData('message_price')?>"/>
                    <?php endif; ?>
                </td>
                <td>Срок реакции на сообщение(сек.):</td>
                <td>
                    <label for="edit-tariff-message-response" class="field-editable"><?=$tariff->getData('message_response')?></label>
                    <input type="text" name="tariff[message_response]" class="hidden" id="edit-tariff-message-response" value="<?=$tariff->getData('message_response')?>"/>
                </td>
            </tr>
        </tbody>
    </table>
    <hr/>
    <button type="button" name="send">Сохранить</button>
    <?php if(false === $tariff->getData('used')): ?><button type="button" name="remove">Удалить</button><?php endif; ?>
</form>
<?php else: ?>
<div><em>Выбранный тариф не существует</em></div>
<?php endif; ?>