<?php
$chainLineWithTariffs = $this->chainLineWithTariffs;
?>
<?php
$jScript = <<<JS
require([
    "dojo/behavior",
    "dojo/hash",
    "app/model/Line",
    "app/model/Level",
    "core/Sandbox",
    "core/sandbox/helpers/Validate",
    "core/sandbox/helpers/Form",
    "core/sandbox/layout/Messenger"]);
dojo.ready(function(){


    //Первоначальная инициализация
    (function(){
        dojo.hash('!/lines');
        Sandbox = new core.Sandbox();
        Messenger = new core.sandbox.layout.Messenger(dojo.byId("messenger"));
    })();



    dojo.subscribe('getTariffs', function(){
        Sandbox.Layout.contentLoader('manager/tariffication/lines', {}).addCallback(function(results){
            Sandbox.Layout.placeContent(dojo.byId('contentTariffs'), results);
            dojo.behavior.apply();
        });
    });

    dojo.subscribe('editTariffInfo', function(args){
        Sandbox.Layout.contentLoader('manager/tariffication/edit-tariff-info', args).addCallback(function(results){
            Sandbox.Layout.placeContent(dojo.byId('contentTariffs'), results);
            dojo.behavior.apply();
            // TODO: Только если тип доступа == writable
            var formNode = dojo.byId("edit-tariff-info");
            if(null !== formNode && "object" === typeof formNode) {

                // Обновление тарифа
                var Validate = new core.sandbox.helpers.Validate(formNode);
                var formSendHandle = dojo.connect(formNode["send"], 'onclick', function(){
                    Validate.clear();
                    Sandbox.Layout.dataSender('manager/tariffication/edit-tariff-info/tariff/' + args.tariff, dojo.formToObject(formNode)).addCallback(function(results){
                        if(results['result'] == args.tariff){
                            setTimeout(function(){
                                Messenger.send({});
                            }, 600);
                        } else {
                            Validate.display(results['error']['messages']);
                        }
                    });
                });

                // Удаление тарифа
                if(true == formNode.hasOwnProperty("remove")) {
                    var remove = dojo.connect(formNode["remove"], "onclick", function(event){
                        Sandbox.Layout.dataSender('manager/tariffication/remove-tariff/tariff/' + args.tariff).addCallback(function(results){
                            if(results['result'] == args.tariff){
                                dojo.disconnect(remove);
                                dojo.disconnect(formSendHandle);
                                dojo.publish('getTariffs');
                            }
                        });
                    });
                }
            }

            return results;
        });
    });

    dojo.subscribe('addTariff', function(args){
        // Форма добавления Пользователей в Группу
        Sandbox.Layout.contentLoader('manager/tariffication/add-tariff', args).addCallback(function(results){
            Sandbox.Layout.Dialog.set("title", "Добавление тарифа");
            Sandbox.Layout.Dialog.set("content", results);
            Sandbox.Layout.Dialog.show();
            var formNode = dojo.byId("add-tariff");
            var Validate = new core.sandbox.helpers.Validate(formNode);
            var formSendHandle = dojo.connect(formNode["send"], "onclick", function(event){
                Sandbox.Layout.dataSender('manager/tariffication/add-tariff', dojo.formToObject(formNode)).addCallback(function(results){
                    Validate.clear();
                    if(results['result'] == -1){
                        Validate.display(results['error']['messages']);
                        //dojo.disconnect(formSendHandle);
                    } else {
                        Sandbox.Layout.Dialog.hide();
                        // Выполнить по истечении срока исчезновения диалога
                        setTimeout(function(){
                            // Обновить группы
                           //dojo.publish('getTariffs');
                        }, /*Sandbox.Layout.Dialog.delay + */Sandbox.Layout.Dialog.duration);
                    }
                });
            });
            //Закрыть диалог
            var dialogHideHandle = dojo.connect(Sandbox.Layout.Dialog, "hide", function(){
                // Отсоединяем все обработчики событий текущего диалога
                dojo.disconnect(formSendHandle);
                dojo.disconnect(dialogHideHandle);
            });
            return results;
        });
    });

    dojo.behavior.add({
        // Получить панель управления ЛК
        '[data-action^="addTariff"]': {
            onclick: function(event){
                event.preventDefault();
                dispatcher(event.target.getAttribute("data-action"), ['line']);
            }
        },
        '[data-action^="#!/editTariffInfo"]': {
            onclick: function(event){
                event.preventDefault();
                dispatcher(event.target.getAttribute("data-action"), ['tariff']);
            }
        }
    });

    dojo.behavior.apply();

    // Диспетчер событий и обработчиков
    function dispatcher(shortLink, argsIndex) {
        var actionParams = Sandbox.Layout.parseShortLink(shortLink);
        dojo.publish(actionParams['action'], Sandbox.Base.indexing(actionParams['args'], argsIndex));
        if(actionParams.hasOwnProperty('prefix')){
            dojo.hash(shortLink);
        }
    }


});
JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript');
?>
<div id="contentTariffs">
    <table class="table table-bordered">
        <colgroup>
            <col width="350">
            <col width="50">
            <col/>
        </colgroup>
        <thead>
        <tr>
            <th colspan="3">Линия Консультации</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($chainLineWithTariffs as $entry):?>
        <tr>
            <td rowspan="<?=count($entry['tariffs']) + 1?>"><?=$entry['line']->getData('name')?></td>
            <th>#ID</th>
            <th>Тариф</th>
        </tr>
        <?php foreach($entry['tariffs'] as $tariff): ?>
        <tr>
            <td><?=$tariff->getData('id')?></td>
            <td><a title="<?=$tariff->getData('name')?>" data-action="#!/editTariffInfo/<?=$tariff->getData('id')?>" class="engineAjax"><?=$tariff->getData('name')?></a></td>
        </tr>
        <?php endforeach; ?>
        <tr>
            <td colspan="3"><div style="text-align: right;"><button type="button" data-action="addTariff/<?=$entry['line']->getData('id')?>">Добавить</button></div></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>