<form id="add-tariff">
<table class="table table-bordered">
    <tfoot>
        <tr>
            <td>
                <input type="hidden" name="line" value="">
                <button type="button" name="send">Сохранить</button>
            </td>
        </tr>
    </tfoot>
    <tbody>
        <tr>
            <td>
                <label for="add-tariff-name">Наименование:</label>
                <input type="text" id="add-tariff-name" name="tariff[name]">
            </td>
        </tr>
    </tbody>
</table>
</form>