<?php
$data = $this->data;
?>
<div id="contentTariffs">
    <table class="table table-bordered">
        <colgroup>
            <col width="350">
            <col width="50">
            <col/>
        </colgroup>
        <thead>
        <tr>
            <th colspan="3">Линия Консультации</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($data as $entry):?>
        <tr>
            <td rowspan="<?=count($entry['tariffs']) + 1?>"><?=$entry['line']->get('name')?></td>
            <th>#ID</th>
            <th>Тариф</th>
        </tr>
            <?php foreach($entry['tariffs'] as $tariff): ?>
            <tr>
                <td><?=$tariff->get('id')?></td>
                <td><a title="<?=$tariff->get('name')?>" data-action="#!/editTariffInfo/<?=$tariff->get('id')?>" class="engineAjax"><?=$tariff->get('name')?></a></td>
            </tr>
                <?php endforeach; ?>
        <tr>
            <td colspan="3"><div style="text-align: right;"><button type="button" data-action="addTariff/10">Добавить</button></div></td>
        </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
