<?php
$user = $this->user;
$agreement= $this->agreement;
?>
<table border="0">
    <tbody align="left">
        <tr>
            <td>
                <p>Уважаемый <strong><?=$user->getData('last_name')?> <?=$user->getData('first_name')?> <?=$user->getData('middle_name')?> (<?=$user->getData('email')?>).</strong><br/>
                    Вы были подписаны на договор #<?=$agreement->getData()->getId()?> от <?=date('m.d.Y', $agreement->getData('date_begin'))?>
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php $tariff = HM_Model_Billing_Tariff::load($agreement->getData('tariff'));?>
                    Линия Консультации: <?=$tariff->getLine()->getData('name')?><br/>
                    Тариф: <?=$tariff->getData('name')?><br/>
                    <?php $company = HM_Model_Billing_Company::load($agreement->getData('company_client'))?>
                    Компания-Клиент: <?=$company->getData('name')?><br/>
                </p>
            </td>
        </tr>
    </tbody>
</table>