<?php
$user = $this->user;
$agreement= $this->agreement;
?>
<table border="0">
    <tbody>
        <tr>
            <td>
                <p>Уважаемый <strong><?=$user->getData('last_name')?> <?=$user->getData('first_name')?> <?=$user->getData('middle_name')?> (<?=$user->getData('email')?>).</strong><br/>
                    Вы были подписаны на договор #<?=$agreement->getData()->getId()?> от <?=date('m.d.Y', $agreement->getData('date_begin'))?>
                </p>
            </td>
        </tr>
        <tr>
            <th>Информация по договору</th>
        </tr>
        <tr>
            <td>
                <p>
                    Линия Консультации: <br/>
                    Тариф: <br/>
                </p>
            </td>
        </tr>
    </tbody>
</table>