<?php
$json = $this->json;
?>
<?php
$jScript = <<<JS
dojo.ready(function(){
var template = Handlebars.compile(dojo.byId("entry-template").innerHTML);
console.log(template({title: "Alan", body: "Johnson", people: ['sdfdsf', 'dfsdfsdf']}));
});
JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript')
?>

<p>Добро пожаловать в систему online помощи - &laquo;Helpme&raquo;</p>
<form id="testme">
    <label for="hello">Тестовое поле</label>
    <input type="text" id="hello" name="level[name]"/>
    <label for="test">Тестовое поле</label>
    <input type="text" id="test" name="level[test]"/>
</form>

<!-- Шаблон для -->
<script id="entry-template" type="text/x-handlebars-template">
    <div class="entry">
        <h1>{{title}}</h1>
        <div class="body">
            {{body}}
            <ul class="people_list">
                {{#each people}}<li>{{this}}</li>{{/each}}
            </ul>
        </div>
    </div>
</script>