<?php
$json = $this->json;
?>
<?php
$jScript = <<<JS
require([]);
dojo.ready(function(){
var template = Handlebars.compile(dojo.byId("entry-template").innerHTML);
console.log(template({title: "Alan", body: "Johnson", people: ['sdfdsf', 'dfsdfsdf']}));

var t = new function(){
    this.test = function(){
        alert('test');
    };

    //this['test'].call(this, []);
};


});
JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript')
?>
<div style="text-align: center; margin: 20px 0">
    <img src="<?php echo $this->baseUrl('theme/default/images/hm.jpg')?>"/>
</div>

<!-- Шаблон для -->
<script id="entry-template" type="text/x-handlebars-template">
    <div class="entry">
        <h1>{{title}}</h1>
        <div class="body">
            {{body}}
            <ul class="people_list">
                {{#each people}}<li>{{this}}</li>{{/each}}
            </ul>
        </div>
    </div>
</script>