<?php
$json = $this->json;
?>
<?php
$jScript = <<<JS
require([
    "core/Ajax",
    "dojo/_base/lang",
    "dojo/Deferred",
    "dojo/request/xhr",
    "core/layout/Msg",
    "app/widgets/SearchCompany"
], function(Ajax, lang, Deferred, xhr, Msg, SC){
    dojo.ready(function(){

        var sc = new SC();
        sc.show();

/*        var t = Ajax.load('http://192.168.1.51/default/index/ajax', {
            handleAs: 'text'
        });

        t.then(function(response){
            console.log(response);
        }, function(){
            alert('2');
        });*/
            //console.log(t);



        //process.cancel();
        //process.reject('PROCESS_STATE_WAITING');
        //process.resolve('fffff');

/*        var deferred = xhr('http://192.168.1.51/default/index/ajax', {
            method: 'post',
            handleAs: 'text',
            timeout: 3000
        });*/




        var deferred = new Deferred(function(){
            alert('Cancel');
        });

/*        setTimeout(function(){
          deferred.resolve("success");
        }, 400);*/

/*        setTimeout(function(){
          //deferred.reject("ooops");
        }, 1000);

        setTimeout(function(){
          deferred.cancel("process");
        }, 900);*/

        //deferred.progress(update);

        deferred.then(function(value){
            // Do something when the process completes
            alert(value);
            var f = new Deferred();
            setTimeout(function(){
                f.resolve("success2");
            }, 1000);
            return f.promise;
        }, function(err){
            // Do something when the process errors out
            alert(err + 'Error');
        }).then(function(value){
            alert(value);
        })

    });
});
JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript')
?>
<div style="text-align: center; margin: 20px 0 0; padding: 100px 0; background: #f3f3f3;">
    <img src="<?php echo $this->baseUrl('theme/default/images/hm.jpg')?>"/>
</div>
<form id="testform">
    <label for="_1_">f</label>
    <input type="text" id="_1_" name="account" required="true">
</form>
<!-- Шаблон для -->
<script id="entry-template" type="text/x-handlebars-template">
    <div class="entry">
        <h1>{{title}}</h1>
        <div class="body">
            {{body}}
            <ul class="people_list">
                {{#each people}}<li>{{this}}</li>{{/each}}
            </ul>
        </div>
    </div>
</script>