<?php
$json = $this->json;
?>
<?php
$jScript = <<<JS
require([
    "dojo/query",
    "core/Ajax",
    "dojo/_base/lang",
    "dojo/Deferred",
    "dojo/request/xhr",
    "core/layout/Msg",
    "app/widgets/SearchCompany",
    "core/layout/Overlay",
    "dijit/layout/ContentPane",
    "dojo/aspect",
    "dojo/store/JsonRest",
    "dojo/io-query"
], function(query, Ajax, lang, Deferred, xhr, Msg, SC, Overlay, ContentPane, aspect, JsonRest, ioQuery){
    dojo.ready(function(){

        var cp = new ContentPane({

        });

        cp.set('content', '<p>Hello World</p>');
        cp.set('id', 'hello');
        cp.placeAt('lt');
        //domStyle.set(registry.byId("myThinger").domNode, "display", "none");
        console.log(cp);

/*        var Messenger = new Msg({
            domNode: 'messenger'
        });
        var handler = Messenger.send('PROCESS_LOAD');
        handler.show();
        setTimeout(function(){
            var handler2 = Messenger.send('PROCESS_STATE_ABORTED');
            handler2.show();
                        var handler3 = Messenger.send('PROCESS_STATE_ABORTED');
            handler3.show();
        }, 1000);*/


        var sc = new SC();
        sc.show();

        setTimeout(function(){
            //sc.show();
        }, 5000);

/*        var o = new Overlay({
            domNode: 'lt'
        });

        o.show();
        setTimeout(function(){
            //o.hide();
        }, 1000);

                    setTimeout(function(){
                //o.show();
            }, 3000);*/


/*        var t = Ajax.load('http://192.168.1.51/default/index/ajax', {
            handleAs: 'json',
            overlay: new Overlay({
                domNode: query('.container')[0]
            })
        });*/




        //process.cancel();
        //process.reject('PROCESS_STATE_WAITING');
        //process.resolve('fffff');

/*        var deferred = xhr('http://192.168.1.51/default/index/ajax', {
            method: 'post',
            handleAs: 'text',
            timeout: 3000
        });*/




        var deferred = new Deferred(function(){
            alert('Cancel');
        });

/*        setTimeout(function(){
          deferred.resolve("success");
        }, 400);*/

/*        setTimeout(function(){
          deferred.reject("ooops");
        }, 900);*/

/*        setTimeout(function(){
          deferred.cancel("process");
        }, 2000);*/

        //deferred.progress(update);

        deferred.then(function(value){
            // Do something when the process completes
            alert(value);

        }, function(err){
            // Do something when the process errors out
            alert(err + 'Error');
            console.log(deferred.isCanceled());
        });


        var rest = new JsonRest({
            target: "/api/1/company/"
        });

        var query = ioQuery.objectToQuery({
            'filters[equal][inn][]': 15
        });

        rest.query('query' + "?" + query, {
            'filters[equal][company][inn][]': 'f',
            start: 10,
            count: 10,
            sort: [
              { attribute: "baz", descending: true }
            ]
        });


/*var userMemoryStore = new dojo.store.Memory();
var userJsonRestStore = new dojo.store.JsonRest({target: "/users/"});
var userStore = new dojo.store.Cache(userJsonRestStore, userMemoryStore);*/

        //'action=company/15/agreement';
        function trace(path){
            var obj = {}, parts = path.match(/#?(\w+)=?(.+)*/i);
            obj.action = parts[1];
            var params = parts[2].split('/');
            for(var i = 0, l = params.length; i < l; i ++){
                obj[params[i]] = params[i+1];
                i += 1;
            }
            return obj;
        }

    });
});
JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript')
?>
<div id="lt" style="width: auto; height: auto; background: green"></div>
<div style="text-align: center; margin: 20px 0 0; padding: 100px 0; background: #f3f3f3;">
    <img src="<?php echo $this->baseUrl('theme/default/images/hm.jpg')?>"/>
</div>
<form id="testform">
    <label for="_1_">f</label>
    <input type="text" id="_1_" name="account" required="true">
</form>
<!-- Шаблон для -->
<script id="entry-template" type="text/x-handlebars-template">
    <div class="entry">
        <h1>{{title}}</h1>
        <div class="body">
            {{body}}
            <ul class="people_list">
                {{#each people}}<li>{{this}}</li>{{/each}}
            </ul>
        </div>
    </div>
</script>
<a data-action="company/15/"