<?php
$guest = $this->guest;
?>
<table border="0">
    <tbody>
        <thead>
            <tr>
                <p>Уважаемый <strong><?=$guest->getData('last_name')?> <?=$guest->getData('first_name')?> <?=$guest->getData('middle_name')?> (<?=$guest->getData('email')?>).</strong><br/>
                Ваш электронный ящик был указан в приглашении в систему HELPME.
                </p>
            </tr>
            <tr>
                <p>Чтобы активировать данную операцию, перейдите, пожалуйста, по ссылке:<br/>
                <a href="<?=$this->baseUrl('account/invite/activate/g/' . $guest->getData('hash_activation'))?>">
                    <?=$this->baseUrl('account/invite/activate/g/' . $guest->getData('hash_activation'))?></a></p>
            </tr>
            <tr>
                <p><em><strong>Внимание!</strong> Если данная операция была инициирована не вами, проигнорируйте данное письмо.</em></p>
            </tr>
        </thead>
    </tbody>
</table>