<?php
$guest = $this->guest;
?>
<table border="0">
    <tbody>
        <tr>
            <td>
                <p>Уважаемый <strong><?=$guest->getData('last_name')?> <?=$guest->getData('first_name')?> <?=$guest->getData('middle_name')?> (<?=$guest->getData('email')?>).</strong><br/>
                    Вы получили приглашение в сервис удаленной поддержки и обслуживания пользователей HelpMe.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>Данное приглашение необходимо активировать. Для этого, перейдите, пожалуйста, по ссылке:<br/>
                    <a href="<?=$this->baseUrl('account/invite/activate/g/' . $guest->getData('hash_activation'))?>">
                        <?=$this->baseUrl('account/invite/activate/g/' . $guest->getData('hash_activation'))?></a></p>
            </td>
       </tr>
        <tr>
            <td>
                <p><em><strong>Внимание!</strong> Если данная операция была инициирована не вами, проигнорируйте данное письмо.</em></p>
            </td>
        </tr>
    </tbody>
</table>