<?php
/**
 * Product: HELPME
 * @author: GaltsinAK
 */
/**
 * Системный шаблон "по умолчанию"
 */
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headMeta();?>
    <?php echo $this->headTitle(); ?>
    <?php print $this->headLink();?>
    <script type="text/javascript">
        // Dojo configuration
        var djConfig = {
            parseOnLoad: true,
            isDebug: true,
            packages: [
                {name: "core", location: '../../core'},
                {name: "app", location: '../../app'}
            ]
        };
        // Application configuration
        var appConfig = {
            baseUrl: "<?=$this->baseUrl();?>",
            serverTimestamp: <?=date('U');?>
        };
    </script>
    <?php print $this->headScript();?>
</head>
<body class="hm" style="position: relative">
<div id="loader" class="_hidden"></div>
<div id="messenger" style="opacity: 0">dsf</div>
<div id="header">
    <div style="background: #F5FAFF; border-bottom: 3px solid #666;">
        <div class="container" style="position: relative; padding: 10px 0">
            <h1>
                <a href="<?php echo $this->baseUrl(); ?>">
                    <img src="<?php echo $this->baseUrl('theme/default/images/logo.jpg')?>"/>
                </a>
            </h1>
            <div style="position: absolute; right: 0; top: 0">
                <!-- Account Bar -->
                <?php if(HM_Model_Account_Auth::getInstance()->isAuth()) :?>
                <?php
                $accountIdentity = HM_Model_Account_Auth::getInstance()->getAccount();
                $userColl = new HM_Model_Account_User_Collection();
                $user = $userColl->load($accountIdentity['user']);
                ?>
                <table>
                    <tr>
                        <td>
                            <?php if(is_string($user->getData('logo'))) :?>
                            <img width="60" height="78" style="width: 60px; height: 78px; border: 1px solid #C7CED6" src="data:image/png;base64,<?=$user->getData('logo')?>">
                            <?php else: ?>
                            <img width="60" height="78" style="width: 60px; height: 78px; border: 1px solid #C7CED6" src="<?=$this->baseUrl('theme/default/images/not_image.png')?>">
                            <?php endif; ?>
                        </td>
                        <td>
                            <div>
                                <strong><?php echo $user->getData('email'); ?> / <?php echo $user->getData('login'); ?></strong> (id: <?php echo $user->getData('id'); ?>)<br/>
                                <a href="<?php echo $this->baseUrl('account/access/logout');?>">Выход</a>
                            </div>
                        </td>
                    </tr>
                </table>
                <?php else: ?>
                <table>
                    <tr>
                        <td>
                            <a href="<?php echo $this->baseUrl('account/access/login');?>">Авторизация</a>
                        </td>
                    </tr>
                </table>
                <?php endif; ?>
                <!-- Account Bar End -->
            </div>
        </div>

    </div>
</div>

<div class="container">
    <!-- Top navbar -->
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li><a>Договора</a></li>
                        <li><a href="<?=$this->baseUrl('manager/tariffication/lines')?>">Тарифы</a></li>
                        <li><a href="<?=$this->baseUrl('manager/counseling-structure/lines')?>">Линии Консультации</a></li>
                        <li><a href="<?=$this->baseUrl('manager/counseling-structure/groups')?>">Группы/Специалисты</a></li>
                        <li><a href="<?=$this->baseUrl('manager/possibility/managers')?>">Настройка доступа</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Top navbar End-->
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>