<?php
/**
 * Product: HELPME
 * @author: GaltsinAK
 */
/**
 * Шаблон для использования электронных сообщений
 */
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?php echo $this->headMeta();?>
        <title><?php echo $this->layout()->subject; ?></title>
	</head>
	<body>
        <?php echo $this->layout()->content; ?>
	</body>
</html>