<form id="search-account">
<table class="table table-bordered">
    <tfoot>
        <tr>
            <td>
                <button type="button" data-action="searchAccount" name="send">Найти</button>
            </td>
        </tr>
    </tfoot>
    <tbody>
        <tr>
            <td>
                <label for="search-account-account">Логин или email:</label>
                <input type="text" id="search-account-account" name="account"/>
            </td>
        </tr>
    </tbody>
</table>
</form>
<form id="add-group-experts">
<table class="table table-bordered" id="table-add-group-experts">
    <colgroup>
        <col width="50"/>
        <col width="60"/>
        <col width="200"/>
        <col width="400"/>
    </colgroup>
    <thead>
    <tr>
        <th>#ID</th>
        <th>Фото</th>
        <th>Логин</th>
        <th>Ф.И.О</th>
    </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="4">
                <button type="button" name="send">Сохранить</button>
            </td>
        </tr>
    </tfoot>
    <tbody>
    </tbody>
</table>
</form>