<?php
/**
 * Product: HELPME
 * @author: GaltsinAK
 */
/**
 * Шаблон для редактирования и просмотра информации об ЛК
 */
?>
<?php
$data = $this->data;
?>
<?php
/**
 * Режим редактирования
 */
if(true === $this->is_writable):
?>
<?php if(is_string($data->get('logo'))) :?>
<img src="data:image/png;base64,<?=$data->get('logo')?>">
<?php else: ?>
<img width="60" height="78" style="width: 60px; height: 78px; border: 2px solid #999" src="<?=$this->baseUrl('theme/default/images/not_image.png')?>">
<?php endif; ?>

<form id="edit-line" method="post">
    <label for="edit-line-name">Наименование:</label>
    <input type="text" value="<?=$data->get('name')?>" id="edit-line-name" name="line[name]"/>
    <label for="edit-line-description">Описание:</label>
    <textarea id="edit-line-description" name="line[description]"><?=$data->get('description')?></textarea><br/>
    <button type="button">Сохранить</button>
</form>

<?php
/**
 * Режим чтения
 */
else:
?>
<table class="table table-bordered">
    <tbody>
        <tr>
            <td>
                <?php if(is_string($data->get('logo'))) :?>
                <img src="data:image/png;base64,<?=$data->get('logo')?>">
                <?php else: ?>
                <img width="60" height="78" style="width: 60px; height: 78px; border: 2px solid #999" src="<?=$this->baseUrl('theme/default/images/not_image.png')?>">
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>
                <strong>#ID:</strong> <?=$data->get('id')?>
            </td>
        </tr>
        <tr>
            <td>
                <strong>Наименование:</strong> &laquo;<?=$data->get('name')?>&raquo;
            </td>
        </tr>
        <tr>
            <td>
                <strong>Описание:</strong><br/>
                <em><?=$data->get('description')?></em>
            </td>
        </tr>
    </tbody>
</table>
<?php
endif;
?>