<?php
$data = $this->data;
?>
<?php if(count($data) > 0):?>
<form id="edit-rules">
    <table class="table table-striped table-bordered">
        <colgroup>
            <col width="50"/>
            <col width="300"/>
            <col width="300"/>
            <col width="200"/>
            <col/>
        </colgroup>
        <thead>
        <tr>
            <th>#ID</th>
            <th>Отправитель</th>
            <th>Получатель</th>
            <th>Время реакции</th>
            <th>Включено</th>
        </tr>
        </thead>
        <tbody>

            <?php foreach($data as $rule): ?>
        <tr>
            <td><?=$rule->get('id'); ?></td>
            <td><?=$rule->get('name_level_from'); ?></td>
            <td><?=$rule->get('name_level_to'); ?></td>
            <td><input name="rules[<?=$rule->get('id') ?>][duration]" type="text" value="<?=$rule->get('duration'); ?>"/></td>
            <td>
                <?php if(true == $rule->get('is_enabled')): ?>
                <input type="checkbox" name="rules[<?=$rule->get('id') ?>][is_enabled]" value="true" checked="true"/>
                <?php else: ?>
                <input type="checkbox" name="rules[<?=$rule->get('id') ?>][is_enabled]" value="false" />
                <?php endif; ?>
            </td>
        </tr>
            <?php endforeach; ?>
        <tr>
            <td colspan="5">
                <button type="button" value="Сохранить" id="submitRules" onclick="consultationLineRulesCommitChanges(this.form)">Сохранить</button>
            </td>
        </tr>
        </tbody>
    </table>
    <input type="hidden" name="line" value="<?=$this->line->getId();?>"/>
</form>
<?php endif; ?>