<?php
$chainCompanyWithLines = $this->chainCompanyWithLines;
?>
<table class="table table-bordered">
    <colgroup>
        <col width="350"/>
        <col width="30"/>
        <col width="50%"/>
        <col/>
    </colgroup>
    <thead>
    <tr>
        <th colspan="4">Название компании</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($chainCompanyWithLines as $entry):
        ?>
    <tr>
        <td rowspan="<?=count($entry['lines']) + 1?>"><?=$entry['company']->getData('name')?></td>
        <th>#ID</th>
        <th>Линия Консультации</th>
        <th>Опции</th>
    </tr>
        <?php
        foreach($entry['lines'] as $line):
            ?>
        <tr>
            <td><?=$line->getData('id')?></td>
            <td><a class="engineAjax" data-action="getLineBoard/<?=$line->getData('id')?>" title="<?=$line->getData('name')?>"><?=$line->getData('name')?></a></td>
            <td><em>просмотр/редактирование</em></td>
        </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </tbody>
</table>