
<?php
$jScript = <<<JS
require(["dojo/behavior", "dojo/hash", "core/Sandbox", "app/model/Line", "app/model/Level"]);
dojo.ready(function(){
    //Первоначальная инициализация
    (function(){
        dojo.hash('!/lines');
        Sandbox = new core.Sandbox();
    })();


    var Line = new app.model.Line();
    var Level = new app.model.Level();

    // События на текущую страницу
    dojo.behavior.add({
        //#!/lineInfo/{id}
        '[data-hash^="#!/lineBoard"]': {
            onclick: function(event){
                event.preventDefault();
                var hash = event.target.getAttribute("data-hash").slice(1);
                var hashParams = hash.split('/');
                Sandbox.Layout.contentLoader('manager/counseling-structure/get-line-board', {line: hashParams[2]}).addCallback(function(results){
                    Sandbox.Layout.placeContent(dojo.byId('contentLines'), results);
                    dojo.hash(hash);
                    dojo.behavior.apply();
                });
            }
        }
    });

    //События по Линии Консультации
    dojo.behavior.add({
        '[data-hash^="#!/lineInfo"]': {
            onclick: function(event){
                var hash = event.target.getAttribute("data-hash").slice(1);
                var hashParams = hash.split('/');
                Line.getEntity(hashParams[2]).getInfo().addCallback(function(results){
                    Sandbox.Layout.placeContent(dojo.byId('contentLine'), results);
                    dojo.hash(hash);
                    dojo.behavior.apply();
                });
            }
        },
        '[data-hash^="#!/lineLevels"]': {
            onclick: function(event){
                var hash = event.target.getAttribute("data-hash").slice(1);
                var hashParams = hash.split('/');
                Line.getEntity(hashParams[2]).getLevels().addCallback(function(results){
                    Sandbox.Layout.placeContent(dojo.byId('contentLine'), results);
                    dojo.hash(hash);
                    dojo.behavior.apply();
                });
            }
        }
    });

    //События по Уровням
    dojo.behavior.add({
        '[data-action="addLevel"]': {
            onclick: function(event){
                alert("Добавляю уровень...");
            }
        }
    });

    dojo.behavior.apply();
});
JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript');
?>

<?php
$data = $this->data;
$companyColl = new HM_Model_Billing_Company_Collection();
$lineColl = new HM_Model_Counseling_Structure_Line_Collection();
?>
<div id="contentLines">
<table class="table table-bordered">
    <colgroup>
        <col width="350"/>
        <col width="30"/>
        <col width="50%"/>
        <col/>
    </colgroup>
    <thead>
        <tr>
            <th colspan="4">Название компании</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach($data as $entry):
                $companyData = $companyColl->load($entry['company'])->getData();
        ?>
        <tr>
            <td rowspan="<?=count($entry['lines']) + 1?>"><?=$companyData->get('name')?></td>
            <th>#ID</th>
            <th>Линия Консультации</th>
            <th>Опции</th>
        </tr>
        <?php
            foreach($entry['lines'] as $line):
                $lineData = $lineColl->load($line)->getData();
        ?>
        <tr>
            <td><?=$lineData->get('id')?></td>
            <td><a class="engineAjax" data-hash="#!/lineBoard/<?=$lineData->get('id')?>" href="#!/lineInfo/<?=$lineData->get('id')?>" title="<?=$lineData->get('name')?>"><?=$lineData->get('name')?></a></td>
            <td><em>просмотр/редактирование</em></td>
        </tr>
        <?php endforeach; ?>
        <?php endforeach; ?>
    </tbody>
</table>
</div>