<?php
/**
 * Product: HELPME
 * @author: GaltsinAK
 */
/**
 * Шаблон для редактирования ЛК
 */
?>
<?php
$line = $this->line;
?>
<?php
$jScript = <<<JS
require(["dojo/behavior", "core/Sandbox", "core/sandbox/layout/Dialog"]);
dojo.ready(function(){
    Sandbox = new core.Sandbox();

    dojo.behavior.add({
        '[data-action="edit-line"]': {
            onclick: function(){
                Sandbox.Layout.contentLoader('manager/counseling-structure/edit-line', {line: $line}).addCallback(function(results){
                    dojo.byId('content').innerHTML = results;
                });
            }
        },
        '[data-action="get-levels"]': {
            onclick: function(){
                Sandbox.Layout.contentLoader('manager/counseling-structure/get-levels', {line: $line}).addCallback(function(results){
                    dojo.byId('content').innerHTML = results;
                });
            }
        }
    });

    // Оператор new позволяет получить this ссылку на новый объект
    var editRules = new function(){
        var that = this;
        // События
        this.behavior = {
            '[data-action="edit-rules"]': {
                onclick: function(event){
                    that.refresh({line: $line});
                    dojo.behavior.apply();
                }
            },
            '[data-action="save-rules"]': {
                onclick: function(event){
                    that.save(dojo.formToObject(event.target.form));
                }
            }
        };
        // Обновить информацию
        this.refresh = function(args){
            // args = {line}
            Sandbox.Layout.contentLoader('manager/counseling-structure/edit-rules', args).addCallback(function(results){
                Sandbox.Layout.placeContent(dojo.byId('content'), results);
                dojo.behavior.apply();
                console.log(Object.prototype.toString.call(that));
            });
        };
        // Сохранить информацию о переадресации
        this.save = function(data){
            Sandbox.Layout.dataSender('manager/counseling-structure/edit-rules', data).addCallback(function(results){
                if(results.status === 'ok') {
                    var dialog = core.sandbox.layout.Dialog();
                    dialog.show();
                    setTimeout(function(){
                        dialog.hideWithSuccess();
                    }, 0)
                }
            });
        }
    };

    dojo.behavior.add(editRules.behavior);
    dojo.behavior.apply();

});
JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript');
?>
<div style="margin: 15px 0">
    <button type="button" data-action="edit-line">Общее</button>
    <button type="button" data-action="get-levels">Уровни</button>
    <button type="button" data-action="edit-rules">Переадресация</button>
    <button type="button" data-action="get-tariffs">Тарифы</button>
</div>
<div id="content"></div>