
<?php
$jScript = <<<JS
require(["dojo/behavior", "dojo/hash", "core/Sandbox", "app/model/Line", "app/model/Level"]);
dojo.ready(function(){
    //Первоначальная инициализация
    (function(){
        dojo.hash('!/lines');
        Sandbox = new core.Sandbox();
    })();

    var Line = new app.model.Line();
    var Level = new app.model.Level();

    dojo.subscribe('lineBoard', function(args){
        Sandbox.Layout.contentLoader('manager/counseling-structure/get-line-board', {line: args.line}).addCallback(function(results){
            Sandbox.Layout.placeContent(dojo.byId('contentLines'), results);
            dojo.behavior.apply();
            dojo.publish('lineInfo', args);
            return results;
        });
    });

    dojo.subscribe('lineInfo', function(args){
        Line.getEntity(args.line).getInfo().addCallback(function(results){
            Sandbox.Layout.placeContent(dojo.byId('contentLine'), results);
            dojo.behavior.apply();
            return results;
        });
    });

    dojo.subscribe('lineLevels', function(args){
        Line.getEntity(args.line).getLevels().addCallback(function(results){
            Sandbox.Layout.placeContent(dojo.byId('contentLine'), results);
            dojo.behavior.apply();
            return results;
        });
    });

    // События на текущую страницу
    dojo.behavior.add({
        //#!/lineInfo/{id}
        '[data-hash^="#!/lineBoard"]': {
            onclick: function(event){
                event.preventDefault();
                var hashParams = Sandbox.Screen.parseHash(event.target.getAttribute("data-hash"));
                dojo.publish('lineBoard', {line: hashParams.parts[1]});
                dojo.hash(event.target.getAttribute("data-hash"));
            }
        }
    });

    //События по Линии Консультации
    dojo.behavior.add({
        '[data-hash^="#!/lineInfo"]': {
            onclick: function(event){
                var hashParams = Sandbox.Screen.parseHash(event.target.getAttribute("data-hash"));
                dojo.publish('lineInfo', {line: hashParams.parts[1]});
                dojo.hash(event.target.getAttribute("data-hash"));
            }
        },
        '[data-hash^="#!/lineLevels"]': {
            onclick: function(event){
                var hashParams = Sandbox.Screen.parseHash(event.target.getAttribute("data-hash"));
                dojo.publish('lineLevels', {line: hashParams.parts[1]});
                dojo.hash(event.target.getAttribute("data-hash"));
            }
        }
    });

    dojo.behavior.add({
        '[data-hash^="#!/levelInfo"]': {
            onclick: function(event){
                event.preventDefault();
                alert("Смотррим уровень!");
            }
        }
    });

    //События по Уровням
    dojo.behavior.add({
        // Добавить уровень
        '[data-action="addLevel"]': {
            onclick: function(event){
                var hashParams = Sandbox.Screen.parseHash(dojo.hash());
                // Загрузить форму в диалог
                Sandbox.Layout.contentLoader('manager/counseling-structure/add-level', {line: hashParams.parts[1]}).addCallback(function(results){
                    Sandbox.Layout.Dialog.set("content", results);
                    Sandbox.Layout.Dialog.show();
                    // Отправка формы на сервер
                    var formSendHandle = dojo.connect(dojo.byId('add-level')['send'], 'onclick', function(event){
                        Line.getEntity(hashParams.parts[1]).addLevel(dojo.formToObject(event.target.form)).addCallback(function(results){
                            if(results['result'] != -1){
                                Sandbox.Layout.Dialog.hide();
                                // Выполнить по истечении срока исчезновения диалога
                                setTimeout(function(){
                                    // Обновить данные уровней
                                   dojo.publish('lineLevels', {line: hashParams.parts[1]});
                                }, /*Sandbox.Layout.Dialog.delay + */Sandbox.Layout.Dialog.duration);
                            }
                        });
                    });
                    //Закрыть диалог
                    var dialogHideHandle = dojo.connect(Sandbox.Layout.Dialog, "hide", function(){
                        // Отсоединяем все обработчики событий текущего диалога
                        dojo.disconnect(formSendHandle);
                        dojo.disconnect(dialogHideHandle);
                    });
                });

            }
        }
    });

    dojo.behavior.apply();
});
JS;
$this->headScript()->appendScript($jScript, $type = 'text/javascript');
?>

<?php
$data = $this->data;
$companyColl = new HM_Model_Billing_Company_Collection();
$lineColl = new HM_Model_Counseling_Structure_Line_Collection();
?>
<div id="contentLines">
<table class="table table-bordered">
    <colgroup>
        <col width="350"/>
        <col width="30"/>
        <col width="50%"/>
        <col/>
    </colgroup>
    <thead>
        <tr>
            <th colspan="4">Название компании</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach($data as $entry):
                $companyData = $companyColl->load($entry['company'])->getData();
        ?>
        <tr>
            <td rowspan="<?=count($entry['lines']) + 1?>"><?=$companyData->get('name')?></td>
            <th>#ID</th>
            <th>Линия Консультации</th>
            <th>Опции</th>
        </tr>
        <?php
            foreach($entry['lines'] as $line):
                $lineData = $lineColl->load($line)->getData();
        ?>
        <tr>
            <td><?=$lineData->get('id')?></td>
            <td><a class="engineAjax" data-hash="#!/lineBoard/<?=$lineData->get('id')?>" href="#!/lineInfo/<?=$lineData->get('id')?>" title="<?=$lineData->get('name')?>"><?=$lineData->get('name')?></a></td>
            <td><em>просмотр/редактирование</em></td>
        </tr>
        <?php endforeach; ?>
        <?php endforeach; ?>
    </tbody>
</table>
</div>